## 7.1 处理缺失数据

In [1]:
import pandas as pd
import numpy as np

In [2]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])

In [3]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [4]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data[0] = None

In [6]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

### 滤除缺失数据

In [7]:
from numpy import nan as NA

In [8]:
data = pd.Series([1, NA, 3.5, NA, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [9]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [10]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
                     [NA, NA, NA], [NA, 6.5, 3.]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [12]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [13]:
data.dropna(how='all')
# 删除全为NA的行

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [14]:
data[4] = NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [15]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [16]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
df

0         1         2
0 -0.233957       NaN       NaN
1  2.136168       NaN       NaN
2  1.369540       NaN -0.427664
3 -0.526783       NaN -1.166375
4  0.113898  0.934407 -1.114810
5 -0.790966  0.874357 -0.652612
6 -1.419997  0.515944  1.356563

In [17]:
df.dropna()

0         1         2
4  0.113898  0.934407 -1.114810
5 -0.790966  0.874357 -0.652612
6 -1.419997  0.515944  1.356563

In [18]:
df.dropna(thresh=2)
# thresh: 应该是保留至少有n个非NaN数据的行/列

0         1         2
2  1.369540       NaN -0.427664
3 -0.526783       NaN -1.166375
4  0.113898  0.934407 -1.114810
5 -0.790966  0.874357 -0.652612
6 -1.419997  0.515944  1.356563

### 填充缺失数据

In [19]:
df

0         1         2
0 -0.233957       NaN       NaN
1  2.136168       NaN       NaN
2  1.369540       NaN -0.427664
3 -0.526783       NaN -1.166375
4  0.113898  0.934407 -1.114810
5 -0.790966  0.874357 -0.652612
6 -1.419997  0.515944  1.356563

In [20]:
df.fillna(0)

0         1         2
0 -0.233957  0.000000  0.000000
1  2.136168  0.000000  0.000000
2  1.369540  0.000000 -0.427664
3 -0.526783  0.000000 -1.166375
4  0.113898  0.934407 -1.114810
5 -0.790966  0.874357 -0.652612
6 -1.419997  0.515944  1.356563

In [21]:
df.fillna({1: 0.5, 2: 0})
# 实现对不同的列填充不同值

0         1         2
0 -0.233957  0.500000  0.000000
1  2.136168  0.500000  0.000000
2  1.369540  0.500000 -0.427664
3 -0.526783  0.500000 -1.166375
4  0.113898  0.934407 -1.114810
5 -0.790966  0.874357 -0.652612
6 -1.419997  0.515944  1.356563

In [22]:
_ = df.fillna(0, inplace=True)

In [23]:
df

0         1         2
0 -0.233957  0.000000  0.000000
1  2.136168  0.000000  0.000000
2  1.369540  0.000000 -0.427664
3 -0.526783  0.000000 -1.166375
4  0.113898  0.934407 -1.114810
5 -0.790966  0.874357 -0.652612
6 -1.419997  0.515944  1.356563

In [24]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA
df

0         1         2
0  0.336718 -0.663034 -0.460659
1  0.590426  2.398009 -1.733318
2 -0.009181       NaN  0.597845
3 -0.506946       NaN -1.137573
4  0.902514       NaN       NaN
5 -0.099498       NaN       NaN

In [25]:
df.fillna(method='ffill')

0         1         2
0  0.336718 -0.663034 -0.460659
1  0.590426  2.398009 -1.733318
2 -0.009181  2.398009  0.597845
3 -0.506946  2.398009 -1.137573
4  0.902514  2.398009 -1.137573
5 -0.099498  2.398009 -1.137573

In [26]:
df.fillna(method='ffill', limit=2)

0         1         2
0  0.336718 -0.663034 -0.460659
1  0.590426  2.398009 -1.733318
2 -0.009181  2.398009  0.597845
3 -0.506946  2.398009 -1.137573
4  0.902514       NaN -1.137573
5 -0.099498       NaN -1.137573

In [27]:
data = pd.Series([1., NA, 3.5, NA, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [28]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

## 7.2 数据转换

### 移除重复数据

In [29]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                    'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [30]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [31]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [32]:
data['v1'] = range(7)

In [33]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [34]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### 利用函数或映射进行数据转换

In [35]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                              'Pastrami', 'corned beef', 'Bacon',
                              'pastrami', 'honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [36]:
meat_to_animal = {
  'bacon': 'pig',
  'pulled pork': 'pig',
  'pastrami': 'cow',
  'corned beef': 'cow',
  'honey ham': 'pig',
  'nova lox': 'salmon'
}

In [37]:
lowercased = data['food'].str.lower()

In [38]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [39]:
data['animal'] = lowercased.map(meat_to_animal)

In [40]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [41]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [42]:
meat_to_animal['bacon']

'pig'

### 替换值

In [43]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [44]:
data.replace(-999, NA)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [45]:
data.replace([-999, -1000], NA)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [46]:
data.replace([-999, -1000], [NA, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [47]:
data.replace({-999: NA, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### 重命名轴索引

In [48]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [49]:
transform = lambda x: x[:4].upper()

In [50]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [51]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [54]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [57]:
data.rename(index={'OHIO': 'INDIANA'},
           columns={'three':'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [58]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

### 离散化和面元划分

In [59]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [60]:
bins = [18, 25, 35, 60, 100]

In [61]:
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [62]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [63]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [64]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [65]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [66]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [67]:
data = np.random.randn(20)
data

array([-0.80321636, -0.42538419, -0.21946276, -1.29209671, -0.1387785 ,
        0.45443024,  1.8078929 ,  0.69904618, -1.03276624, -0.03847769,
        0.74493892, -0.61413798,  2.03583028, -1.89131997, -2.92357973,
       -0.57721853, -0.2993123 , -1.7900115 , -0.54422774,  1.34792787])

In [71]:
pd.cut(data, 4, precision=2)

[(-1.68, -0.44], (-0.44, 0.8], (-0.44, 0.8], (-1.68, -0.44], (-0.44, 0.8], ..., (-1.68, -0.44], (-0.44, 0.8], (-2.93, -1.68], (-1.68, -0.44], (0.8, 2.04]]
Length: 20
Categories (4, interval[float64]): [(-2.93, -1.68] < (-1.68, -0.44] < (-0.44, 0.8] < (0.8, 2.04]]

In [72]:
data = np.random.randn(1000)

In [73]:
cats = pd.qcut(data, 4)
cats

[(-0.727, 0.0502], (-3.522, -0.727], (-0.727, 0.0502], (-3.522, -0.727], (0.0502, 0.715], ..., (-3.522, -0.727], (0.715, 3.054], (0.715, 3.054], (0.0502, 0.715], (-3.522, -0.727]]
Length: 1000
Categories (4, interval[float64]): [(-3.522, -0.727] < (-0.727, 0.0502] < (0.0502, 0.715] < (0.715, 3.054]]

In [74]:
pd.value_counts(cats)

(0.715, 3.054]      250
(0.0502, 0.715]     250
(-0.727, 0.0502]    250
(-3.522, -0.727]    250
dtype: int64

In [78]:
cats2 = pd.qcut(data, [0, 0.1, 0.5, 0.9, 1])
cats2

[(-1.387, 0.0502], (-3.522, -1.387], (-1.387, 0.0502], (-1.387, 0.0502], (0.0502, 1.243], ..., (-3.522, -1.387], (0.0502, 1.243], (0.0502, 1.243], (0.0502, 1.243], (-1.387, 0.0502]]
Length: 1000
Categories (4, interval[float64]): [(-3.522, -1.387] < (-1.387, 0.0502] < (0.0502, 1.243] < (1.243, 3.054]]

In [79]:
pd.value_counts(cats2)

(0.0502, 1.243]     400
(-1.387, 0.0502]    400
(1.243, 3.054]      100
(-3.522, -1.387]    100
dtype: int64

### 检测和过滤异常值

In [81]:
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.048837    -0.042133    -0.027557     0.007788
std       1.003519     0.978534     1.006060     1.020505
min      -2.789719    -4.075030    -3.603688    -4.219186
25%      -0.729721    -0.697035    -0.679111    -0.680662
50%      -0.052385     0.011585    -0.036656    -0.025591
75%       0.697852     0.661529     0.593408     0.716552
max       3.105089     3.572472     3.561080     3.943981

In [82]:
col = data[2]

In [83]:
col[np.abs(col) > 3]

133    3.561080
261    3.407875
325   -3.088107
488   -3.603688
648   -3.352321
Name: 2, dtype: float64

In [87]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
64   0.872196 -0.920049  0.544693 -4.219186
133 -0.780882 -0.433992  3.561080  1.250591
215 -0.255691  0.435035  0.893941 -3.786509
252  0.682103 -4.075030 -0.233961 -0.567679
261  0.794541  0.906886  3.407875 -0.857001
266 -1.058891  3.204245  0.203066  1.410345
279  0.868913  1.686346 -0.145343  3.943981
325  0.566286  1.239328 -3.088107 -0.069974
421  0.164457 -2.301556 -1.234194  3.070315
488 -1.489730  0.565673 -3.603688 -1.366362
625  3.105089 -0.282539  1.691554  1.124793
648 -2.319095  0.188579 -3.352321 -1.830409
743 -0.165962  3.572472  0.477723 -1.647550
879 -0.554994 -3.061373  0.977426 -0.753254
946 -0.596063  0.732898 -0.516836 -3.297270

In [91]:
data[np.abs(data) > 3] = np.sign(data) * 3

In [92]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.048942    -0.041773    -0.027482     0.009077
std       1.003194     0.971874     0.999546     1.009154
min      -2.789719    -3.000000    -3.000000    -3.000000
25%      -0.729721    -0.697035    -0.679111    -0.680662
50%      -0.052385     0.011585    -0.036656    -0.025591
75%       0.697852     0.661529     0.593408     0.716552
max       3.000000     3.000000     3.000000     3.000000

In [93]:
np.sign(data).head()

0    1    2    3
0  1.0 -1.0 -1.0  1.0
1  1.0  1.0 -1.0 -1.0
2 -1.0  1.0  1.0 -1.0
3  1.0  1.0  1.0  1.0
4  1.0 -1.0  1.0  1.0

### 排列和随机采样

In [94]:
df = pd.DataFrame(np.arange(5*4).reshape((5,4 )))

In [95]:
sampler = np.random.permutation(5)
sampler

array([3, 2, 1, 0, 4])

In [96]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [97]:
df.take(sampler)

0   1   2   3
3  12  13  14  15
2   8   9  10  11
1   4   5   6   7
0   0   1   2   3
4  16  17  18  19

In [101]:
df.sample(n=3)

0   1   2   3
2   8   9  10  11
0   0   1   2   3
4  16  17  18  19

In [106]:
choice = pd.Series([5, 7, -1, 6, 4])
choice

0    5
1    7
2   -1
3    6
4    4
dtype: int64

In [111]:
draws = choice.sample(n=10, replace=True)
draws

2   -1
4    4
4    4
3    6
1    7
4    4
0    5
1    7
4    4
2   -1
dtype: int64

### 计算指标，哑变量

In [112]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                  'data1': range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [113]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [114]:
dummies = pd.get_dummies(df['key'], prefix='key')
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [117]:
type(df['data1'])

pandas.core.series.Series

In [118]:
type(df[['data1']])
# 两个括号， 结果类型是df

pandas.core.frame.DataFrame

In [120]:
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [121]:
df_with_dummy = df['data1'].join(dummies)

AttributeError: 'Series' object has no attribute 'join'

In [122]:
mnames = ['movie_id', 'title', 'genres']

In [123]:
movies = pd.read_table('movies.dat', sep='::', 
                       header=None, names=mnames)

D:\anaconda\anaconda3\lib\site-packages\ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  


In [125]:
movies.head(10)

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [126]:
all_genres = []

In [127]:
for x in movies.genres:
    all_genres.extend(x.split('|'))

In [129]:
genres = pd.unique(all_genres)

In [130]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [139]:
zero_matrix = np.zeros((len(movies), len(genres)))

In [140]:
dummies = pd.DataFrame(zero_matrix, columns=genres)

In [141]:
dummies.head()

Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  Action  \
0        0.0         0.0     0.0        0.0      0.0      0.0    0.0     0.0   
1        0.0         0.0     0.0        0.0      0.0      0.0    0.0     0.0   
2        0.0         0.0     0.0        0.0      0.0      0.0    0.0     0.0   
3        0.0         0.0     0.0        0.0      0.0      0.0    0.0     0.0   
4        0.0         0.0     0.0        0.0      0.0      0.0    0.0     0.0   

   Crime  Thriller  Horror  Sci-Fi  Documentary  War  Musical  Mystery  \
0    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   
1    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   
2    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   
3    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   
4    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   

   Film-Noir  Western  
0        0.0      0.0  
1        0.0      0.0  
2        0.0      0.0  
3        0.0      0.0  
4        0.0      0.0

In [150]:
gen = movies.genres[0]
gen

"Animation|Children's|Comedy"

In [144]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [145]:
dummies.columns

Index(['Animation', 'Children's', 'Comedy', 'Adventure', 'Fantasy', 'Romance',
       'Drama', 'Action', 'Crime', 'Thriller', 'Horror', 'Sci-Fi',
       'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir', 'Western'],
      dtype='object')

In [146]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [147]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

In [157]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [158]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [159]:
np.random.seed(12345)

In [161]:
values = np.random.rand(10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [162]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [166]:
cats = pd.cut(values, bins)

In [167]:
pd.get_dummies(cats)

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

## 7.3 字符串操作

### 字符串对象方法

In [168]:
val = 'a,b, guido'
val.split(',')

['a', 'b', ' guido']

In [169]:
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [170]:
first, second, third = pieces
first + '::' + second + '::' + third

'a::b::guido'

In [171]:
'::'.join(pieces)

'a::b::guido'

In [172]:
'guido' in val

True

In [173]:
' guido' in val

True

In [177]:
val.index('i')
# 对于找不到的，函数报错

7

In [178]:
val.find(':') 
# 对于找不到的，返回-1

-1

In [182]:
val.find('i')

7

In [183]:
val.count(',')

2

In [184]:
val.replace(',', '::')

'a::b:: guido'

In [185]:
val.replace(',', '')

'ab guido'

### 正则表达式

In [186]:
import re

In [188]:
text = 'foo     bar\t baz  \tqux'
print(text)

foo     bar	 baz  	qux


In [189]:
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [190]:
regex = re.compile('\s+')

In [191]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [192]:
regex.findall(text)

['     ', '\t ', '  \t']

In [193]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""

In [228]:
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

In [229]:
regex = re.compile(pattern, re.I)

In [196]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [198]:
m = regex.search(text)
m

<_sre.SRE_Match object; span=(5, 20), match='dave@google.com'>

In [199]:
text[m.start():m.end()]

'dave@google.com'

In [201]:
print(regex.match(text))

None


In [203]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [230]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

regex = re.compile(pattern, flags=re.IGNORECASE)

In [207]:
m = regex.match('wesm@bright.net')

m.groups()

('wesm', 'bright', 'net')

In [208]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [209]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com



### Pandas的矢量化字符串函数

In [231]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com',
        'Rob': 'rob@gmail.com', 'Wes': np.nan}
data

{'Dave': 'dave@google.com',
 'Steve': 'steve@gmail.com',
 'Rob': 'rob@gmail.com',
 'Wes': nan}

In [232]:
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [233]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [234]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [235]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [236]:
data.str.findall(pattern, re.I)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [241]:
matches = data.str.match(pattern, flags = re.IGNORECASE)

In [242]:
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [243]:
matches.str.get(1)

Dave    NaN
Steve   NaN
Rob     NaN
Wes     NaN
dtype: float64

In [244]:
matches.str[0]

Dave    NaN
Steve   NaN
Rob     NaN
Wes     NaN
dtype: float64

In [245]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object